import React from 'react';
import BlueDots from './images/svg/BlueDots';
import BluePlane from './images/svg/BluePlane';
import BookCabSearch from './images/svg/BookCabSearch';
import CalenderBlue from './images/svg/CalenderBlue';
import DotGray from './images/svg/DotGray';
import Filter from './images/svg/Filter';
import GrayCalender from './images/svg/GrayCalender';
import GrayClock from './images/svg/GrayClock';
import GrayContact from './images/svg/GrayContact';
import GrayEmail from './images/svg/GrayEmail';
import GrayPhone from './images/svg/GrayPhone';
import GreenActiveStar from './images/svg/GreenActiveStar';
import GreenHalfStar from './images/svg/GreenHalfStar';
import HeaderBackArrow from './images/svg/HeaderBackArrow';
import Location from './images/svg/Location';
import Lock from './images/svg/Lock';
import LongGrayArrow from './images/svg/LongGrayArrow';
import LongRightBlueArrow from './images/svg/LongRightBlueArrow';
import OppositeArrow from './images/svg/OppositeArrow';
import SearchIndicator from './images/svg/SearchIndicator';
import TrustedPart from './images/svg/TrustedPart';

export const IcBlueDots = props => <BlueDots {...props} />;
export const IcBluePlane = props => <BluePlane {...props} />;
export const IcBookCabSearch = props => <BookCabSearch {...props} />;
export const IcCalenderBlue = props => <CalenderBlue {...props} />;
export const IcDotGray = props => <DotGray {...props} />;
export const IcFilter = props => <Filter {...props} />;
export const IcGrayCalender = props => <GrayCalender {...props} />;
export const IcGrayClock = props => <GrayClock {...props} />;
export const IcGrayContact = props => <GrayContact {...props} />;
export const IcGrayEmail = props => <GrayEmail {...props} />;
export const IcGrayPhone = props => <GrayPhone {...props} />;
export const IcGreenActiveStar = props => <GreenActiveStar {...props} />;
export const IcGreenHalfStar = props => <GreenHalfStar {...props} />;
export const IcHeaderBackArrow = props => <HeaderBackArrow {...props} />;
export const IcLocation = props => <Location {...props} />;
export const IcLock = props => <Lock {...props} />;
export const IcLongGrayArrow = props => <LongGrayArrow {...props} />;
export const IcLongRightBlueArrow = props => <LongRightBlueArrow {...props} />;
export const IcOppositeArrow = props => <OppositeArrow {...props} />;
export const IcSearchIndicator = props => <SearchIndicator {...props} />;
export const IcTrustedPart = props => <TrustedPart {...props} />;
