export const images ={
  hotel: require('./images/images/hotel.jpeg'),
  homepage: require('./images/images/homepage.jpeg'),
  southindia:require('./images/images/southindia.jpeg'),
  rajasthan:require('./images/images/rajasthan.jpeg'),
  delhitemple:require('./images/images/delhitemple.jpeg'),
  building:require('./images/images/building.jpeg'),
  tajmahal:require('./images/images/tajmahal.jpeg'),
  people:require('./images/images/people.jpeg'),
  memorial:require('./images/images/memorial.jpeg'),
  lake:require('./images/images/lake.jpeg'),
  minitaj:require('./images/images/minitaj.jpeg'),
  minakshi:require('./images/images/minakshi.jpeg'),
  drum:require('./images/images/drum.jpeg'),
  sky:require('./images/images/sky.jpeg'),
  vistara:require('./images/images/vistara.jpeg'),
  indigo:require('./images/images/indigo.jpeg'),
  spicejet:require('./images/images/spicejet.png'),
  airindia:require('./images/images/airindia.jpeg'),
  palace:require('./images/images/palace.jpeg'),
  pool:require('./images/images/pool.jpeg'),
  lobby:require('./images/images/lobby.jpeg'),
  dinner:require('./images/images/dinner.jpeg'),
  beach:require('./images/images/beach.jpeg'),
  bedroom:require('./images/images/bedroom.jpeg'),
  peacepool:require('./images/images/peacepool.jpeg'),
  flowerpot:require('./images/images/flowerpot.jpeg'),
  bigpool:require('./images/images/bigpool.jpeg'),
  house:require('./images/images/house.jpeg'),
  classicbedroom:require('./images/images/classicbedroom.jpeg'),
  nightscene:require('./images/images/nightscene.jpeg'),
  food:require('./images/images/food.jpeg'),
  skyscaper:require('./images/images/skyscaper.jpeg'),
  corridor:require('./images/images/corridor.jpeg'),
  livingroom:require('./images/images/livingroom.jpeg'),
  bathroom:require('./images/images/bathroom.jpeg'),
  lady:require('./images/images/lady.jpeg'),
  rupay:require('./images/images/rupay.png'),
  visa:require('./images/images/visa.png'),
  mastercard:require('./images/images/mastercard.jpeg'),
  profile:require('./images/images/profile.jpeg'),

};